name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # JOB 1: The Build Box
  Build-Application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend & Backend
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  # JOB 2: The Test Box (Waits for Build to finish)
  Run-Tests:
    needs: Build-Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend Deps
        run: cd backend && npm install

      - name: Run All 30+ Automated CRUD Tests
        # This will run every .test.js file in your backend folder
        run: cd backend && npm test
        env:
          MONGO_URI: ${{ secrets.URI }}
          JWT_SECRET: ${{ secrets.JWT }}
